export interface CodeSnippet {
  language: 'python' | 'javascript';
  lines: string[];
  lineHighlights: Record<number, string>;
}

export interface AlgorithmCode {
  python: CodeSnippet;
  javascript: CodeSnippet;
}

export const ALGORITHM_CODE: Record<string, AlgorithmCode> = {
  bubbleSort: {
    python: {
      language: 'python',
      lines: [
        'def bubble_sort(arr):',
        '    n = len(arr)',
        '    for i in range(n - 1):',
        '        for j in range(n - i - 1):',
        '            if arr[j] > arr[j + 1]:',
        '                arr[j], arr[j + 1] = arr[j + 1], arr[j]',
        '    return arr',
      ],
      lineHighlights: {
        2: '外层循环开始',
        3: '内层循环开始',
        4: '比较相邻元素',
        5: '如果左边大于右边',
        6: '交换元素',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function bubbleSort(arr) {',
        '    const n = arr.length;',
        '    for (let i = 0; i < n - 1; i++) {',
        '        for (let j = 0; j < n - i - 1; j++) {',
        '            if (arr[j] > arr[j + 1]) {',
        '                [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];',
        '            }',
        '        }',
        '    }',
        '    return arr;',
        '}',
      ],
      lineHighlights: {
        2: '获取数组长度',
        3: '外层循环',
        4: '内层循环',
        5: '比较相邻元素',
        6: '交换元素',
      },
    },
  },
  selectionSort: {
    python: {
      language: 'python',
      lines: [
        'def selection_sort(arr):',
        '    n = len(arr)',
        '    for i in range(n - 1):',
        '        min_idx = i',
        '        for j in range(i + 1, n):',
        '            if arr[j] < arr[min_idx]:',
        '                min_idx = j',
        '        arr[i], arr[min_idx] = arr[min_idx], arr[i]',
        '    return arr',
      ],
      lineHighlights: {
        2: '获取数组长度',
        3: '外层循环',
        4: '假设最小值索引',
        5: '内层循环查找最小值',
        6: '更新最小值索引',
        7: '交换元素到正确位置',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function selectionSort(arr) {',
        '    const n = arr.length;',
        '    for (let i = 0; i < n - 1; i++) {',
        '        let minIdx = i;',
        '        for (let j = i + 1; j < n; j++) {',
        '            if (arr[j] < arr[minIdx]) {',
        '                minIdx = j;',
        '            }',
        '        }',
        '        [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];',
        '    }',
        '    return arr;',
        '}',
      ],
      lineHighlights: {
        2: '获取数组长度',
        3: '外层循环',
        4: '假设最小值索引',
        5: '内层循环查找最小值',
        6: '更新最小值索引',
        9: '交换元素到正确位置',
      },
    },
  },
  insertionSort: {
    python: {
      language: 'python',
      lines: [
        'def insertion_sort(arr):',
        '    for i in range(1, len(arr)):',
        '        key = arr[i]',
        '        j = i - 1',
        '        while j >= 0 and arr[j] > key:',
        '            arr[j + 1] = arr[j]',
        '            j -= 1',
        '        arr[j + 1] = key',
        '    return arr',
      ],
      lineHighlights: {
        2: '从第二个元素开始',
        3: '保存当前元素',
        4: '初始化比较位置',
        5: '向前移动较大元素',
        6: '元素右移',
        7: '移动指针',
        8: '插入到正确位置',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function insertionSort(arr) {',
        '    for (let i = 1; i < arr.length; i++) {',
        '        const key = arr[i];',
        '        let j = i - 1;',
        '        while (j >= 0 && arr[j] > key) {',
        '            arr[j + 1] = arr[j];',
        '            j--;',
        '        }',
        '        arr[j + 1] = key;',
        '    }',
        '    return arr;',
        '}',
      ],
      lineHighlights: {
        2: '从第二个元素开始',
        3: '保存当前元素',
        4: '初始化比较位置',
        5: '向前移动较大元素',
        6: '元素右移',
        7: '移动指针',
        9: '插入到正确位置',
      },
    },
  },
  quickSort: {
    python: {
      language: 'python',
      lines: [
        'def quick_sort(arr, low, high):',
        '    if low < high:',
        '        pi = partition(arr, low, high)',
        '        quick_sort(arr, low, pi - 1)',
        '        quick_sort(arr, pi + 1, high)',
        '',
        'def partition(arr, low, high):',
        '    pivot = arr[high]',
        '    i = low - 1',
        '    for j in range(low, high):',
        '        if arr[j] < pivot:',
        '            i += 1',
        '            arr[i], arr[j] = arr[j], arr[i]',
        '    arr[i + 1], arr[high] = arr[high], arr[i + 1]',
        '    return i + 1',
      ],
      lineHighlights: {
        2: '基本情形',
        3: '分区操作',
        4: '递归排序左半部分',
        5: '递归排序右半部分',
        9: '选择枢轴元素',
        10: '初始化指针',
        11: '遍历数组',
        12: '小于枢轴',
        13: '交换小于枢轴的元素',
        15: '将枢轴放到正确位置',
        16: '返回枢轴索引',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function quickSort(arr, low, high) {',
        '    if (low < high) {',
        '        const pi = partition(arr, low, high);',
        '        quickSort(arr, low, pi - 1);',
        '        quickSort(arr, pi + 1, high);',
        '    }',
        '}',
        '',
        'function partition(arr, low, high) {',
        '    const pivot = arr[high];',
        '    let i = low - 1;',
        '    for (let j = low; j < high; j++) {',
        '        if (arr[j] < pivot) {',
        '            i++;',
        '            [arr[i], arr[j]] = [arr[j], arr[i]];',
        '        }',
        '    }',
        '    [arr[i + 1], arr[high]] = [arr[high], arr[i + 1]];',
        '    return i + 1;',
        '}',
      ],
      lineHighlights: {
        2: '基本情形',
        3: '分区操作',
        4: '递归排序左半部分',
        5: '递归排序右半部分',
        9: '选择枢轴元素',
        10: '初始化指针',
        11: '遍历数组',
        12: '小于枢轴',
        13: '指针右移',
        14: '交换元素',
        17: '将枢轴放到正确位置',
        18: '返回枢轴索引',
      },
    },
  },
  mergeSort: {
    python: {
      language: 'python',
      lines: [
        'def merge_sort(arr):',
        '    if len(arr) > 1:',
        '        mid = len(arr) // 2',
        '        L = arr[:mid]',
        '        R = arr[mid:]',
        '        merge_sort(L)',
        '        merge_sort(R)',
        '        merge(arr, L, R)',
        '',
        'def merge(arr, L, R):',
        '    i = j = k = 0',
        '    while i < len(L) and j < len(R):',
        '        if L[i] <= R[j]:',
        '            arr[k] = L[i]',
        '            i += 1',
        '        else:',
        '            arr[k] = R[j]',
        '            j += 1',
        '        k += 1',
      ],
      lineHighlights: {
        2: '基本情形',
        3: '找中点',
        4: '左半部分',
        5: '右半部分',
        6: '递归排序左半部分',
        7: '递归排序右半部分',
        8: '合并两半部分',
        12: '初始化指针',
        13: '比较并合并',
        14: '左边元素较小',
        15: '复制左边元素',
        17: '右边元素较小',
        18: '复制右边元素',
        20: '移动指针',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function mergeSort(arr) {',
        '    if (arr.length > 1) {',
        '        const mid = Math.floor(arr.length / 2);',
        '        const L = arr.slice(0, mid);',
        '        const R = arr.slice(mid);',
        '        mergeSort(L);',
        '        mergeSort(R);',
        '        merge(arr, L, R);',
        '    }',
        '}',
        '',
        'function merge(arr, L, R) {',
        '    let i = j = k = 0;',
        '    while (i < L.length && j < R.length) {',
        '        if (L[i] <= R[j]) {',
        '            arr[k] = L[i];',
        '            i++;',
        '        } else {',
        '            arr[k] = R[j];',
        '            j++;',
        '        }',
        '        k++;',
        '    }',
        '}',
      ],
      lineHighlights: {
        2: '基本情形',
        3: '找中点',
        4: '左半部分',
        5: '右半部分',
        6: '递归排序左半部分',
        7: '递归排序右半部分',
        8: '合并两半部分',
        12: '初始化指针',
        13: '比较并合并',
        14: '左边元素较小',
        15: '复制左边元素',
        17: '右边元素较小',
        18: '复制右边元素',
        20: '移动指针',
      },
    },
  },
  heapSort: {
    python: {
      language: 'python',
      lines: [
        'def heap_sort(arr):',
        '    n = len(arr)',
        '    for i in range(n // 2 - 1, -1, -1):',
        '        heapify(arr, n, i)',
        '    for i in range(n - 1, 0, -1):',
        '        arr[0], arr[i] = arr[i], arr[0]',
        '        heapify(arr, i, 0)',
        '',
        'def heapify(arr, n, i):',
        '    largest = i',
        '    left = 2 * i + 1',
        '    right = 2 * i + 2',
        '    if left < n and arr[left] > arr[largest]:',
        '        largest = left',
        '    if right < n and arr[right] > arr[largest]:',
        '        largest = right',
        '    if largest != i:',
        '        arr[i], arr[largest] = arr[largest], arr[i]',
        '        heapify(arr, n, largest)',
      ],
      lineHighlights: {
        2: '获取数组长度',
        3: '构建最大堆',
        4: '堆化操作',
        6: '逐个提取元素',
        7: '交换堆顶和末尾',
        8: '堆化根节点',
        12: '堆化函数',
        13: '初始化为根节点',
        14: '左子节点',
        15: '右子节点',
        16: '左子节点更大',
        18: '右子节点更大',
        20: '需要交换',
        21: '交换元素',
        22: '递归堆化',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function heapSort(arr) {',
        '    const n = arr.length;',
        '    for (let i = Math.floor(n / 2) - 1; i >= 0; i--) {',
        '        heapify(arr, n, i);',
        '    }',
        '    for (let i = n - 1; i > 0; i--) {',
        '        [arr[0], arr[i]] = [arr[i], arr[0]];',
        '        heapify(arr, i, 0);',
        '    }',
        '}',
        '',
        'function heapify(arr, n, i) {',
        '    let largest = i;',
        '    const left = 2 * i + 1;',
        '    const right = 2 * i + 2;',
        '    if (left < n && arr[left] > arr[largest]) {',
        '        largest = left;',
        '    }',
        '    if (right < n && arr[right] > arr[largest]) {',
        '        largest = right;',
        '    }',
        '    if (largest !== i) {',
        '        [arr[i], arr[largest]] = [arr[largest], arr[i]];',
        '        heapify(arr, n, largest);',
        '    }',
        '}',
      ],
      lineHighlights: {
        2: '获取数组长度',
        3: '构建最大堆',
        4: '堆化操作',
        6: '逐个提取元素',
        7: '交换堆顶和末尾',
        8: '堆化根节点',
        12: '堆化函数',
        13: '初始化为根节点',
        14: '左子节点',
        15: '右子节点',
        16: '左子节点更大',
        18: '右子节点更大',
        20: '需要交换',
        21: '交换元素',
        22: '递归堆化',
      },
    },
  },
  linearSearch: {
    python: {
      language: 'python',
      lines: [
        'def linear_search(arr, target):',
        '    for i in range(len(arr)):',
        '        if arr[i] == target:',
        '            return i',
        '    return -1',
      ],
      lineHighlights: {
        2: '遍历数组',
        3: '检查是否匹配',
        4: '找到目标，返回索引',
        5: '未找到，返回-1',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function linearSearch(arr, target) {',
        '    for (let i = 0; i < arr.length; i++) {',
        '        if (arr[i] === target) {',
        '            return i;',
        '        }',
        '    }',
        '    return -1;',
        '}',
      ],
      lineHighlights: {
        2: '遍历数组',
        3: '检查是否匹配',
        4: '找到目标，返回索引',
        6: '未找到，返回-1',
      },
    },
  },
  binarySearch: {
    python: {
      language: 'python',
      lines: [
        'def binary_search(arr, target):',
        '    left, right = 0, len(arr) - 1',
        '    while left <= right:',
        '        mid = (left + right) // 2',
        '        if arr[mid] == target:',
        '            return mid',
        '        elif arr[mid] < target:',
        '            left = mid + 1',
        '        else:',
        '            right = mid - 1',
        '    return -1',
      ],
      lineHighlights: {
        2: '初始化左右边界',
        3: '循环条件',
        4: '计算中点',
        5: '找到目标',
        7: '目标在右半部分',
        9: '目标在左半部分',
        11: '未找到',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function binarySearch(arr, target) {',
        '    let left = 0;',
        '    let right = arr.length - 1;',
        '    while (left <= right) {',
        '        const mid = Math.floor((left + right) / 2);',
        '        if (arr[mid] === target) {',
        '            return mid;',
        '        } else if (arr[mid] < target) {',
        '            left = mid + 1;',
        '        } else {',
        '            right = mid - 1;',
        '        }',
        '    }',
        '    return -1;',
        '}',
      ],
      lineHighlights: {
        2: '初始化左边界',
        3: '初始化右边界',
        4: '循环条件',
        5: '计算中点',
        6: '找到目标',
        8: '目标在右半部分',
        10: '目标在左半部分',
        13: '未找到',
      },
    },
  },
  preorder: {
    python: {
      language: 'python',
      lines: [
        'def preorder(node):',
        '    if node is None:',
        '        return',
        '    print(node.val)',
        '    preorder(node.left)',
        '    preorder(node.right)',
      ],
      lineHighlights: {
        2: '基本情形：空节点',
        3: '返回',
        4: '访问根节点',
        5: '递归遍历左子树',
        6: '递归遍历右子树',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function preorder(node) {',
        '    if (node === null) {',
        '        return;',
        '    }',
        '    console.log(node.val);',
        '    preorder(node.left);',
        '    preorder(node.right);',
        '}',
      ],
      lineHighlights: {
        2: '基本情形：空节点',
        3: '返回',
        5: '访问根节点',
        6: '递归遍历左子树',
        7: '递归遍历右子树',
      },
    },
  },
  inorder: {
    python: {
      language: 'python',
      lines: [
        'def inorder(node):',
        '    if node is None:',
        '        return',
        '    inorder(node.left)',
        '    print(node.val)',
        '    inorder(node.right)',
      ],
      lineHighlights: {
        2: '基本情形：空节点',
        3: '返回',
        4: '递归遍历左子树',
        5: '访问根节点',
        6: '递归遍历右子树',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function inorder(node) {',
        '    if (node === null) {',
        '        return;',
        '    }',
        '    inorder(node.left);',
        '    console.log(node.val);',
        '    inorder(node.right);',
        '}',
      ],
      lineHighlights: {
        2: '基本情形：空节点',
        3: '返回',
        5: '递归遍历左子树',
        6: '访问根节点',
        7: '递归遍历右子树',
      },
    },
  },
  postorder: {
    python: {
      language: 'python',
      lines: [
        'def postorder(node):',
        '    if node is None:',
        '        return',
        '    postorder(node.left)',
        '    postorder(node.right)',
        '    print(node.val)',
      ],
      lineHighlights: {
        2: '基本情形：空节点',
        3: '返回',
        4: '递归遍历左子树',
        5: '递归遍历右子树',
        6: '访问根节点',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function postorder(node) {',
        '    if (node === null) {',
        '        return;',
        '    }',
        '    postorder(node.left);',
        '    postorder(node.right);',
        '    console.log(node.val);',
        '}',
      ],
      lineHighlights: {
        2: '基本情形：空节点',
        3: '返回',
        5: '递归遍历左子树',
        6: '递归遍历右子树',
        7: '访问根节点',
      },
    },
  },
  bfs: {
    python: {
      language: 'python',
      lines: [
        'from collections import deque',
        '',
        'def bfs(graph, start):',
        '    visited = set()',
        '    queue = deque([start])',
        '    visited.add(start)',
        '    ',
        '    while queue:',
        '        node = queue.popleft()',
        '        print(node)',
        '        for neighbor in graph[node]:',
        '            if neighbor not in visited:',
        '                visited.add(neighbor)',
        '                queue.append(neighbor)',
      ],
      lineHighlights: {
        4: '初始化访问集合',
        5: '初始化队列',
        6: '标记起始节点',
        8: '队列不为空',
        9: '出队节点',
        10: '访问节点',
        11: '遍历邻居',
        12: '未访问',
        13: '标记已访问',
        14: '邻居入队',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function bfs(graph, start) {',
        '    const visited = new Set();',
        '    const queue = [start];',
        '    visited.add(start);',
        '    ',
        '    while (queue.length > 0) {',
        '        const node = queue.shift();',
        '        console.log(node);',
        '        for (const neighbor of graph[node]) {',
        '            if (!visited.has(neighbor)) {',
        '                visited.add(neighbor);',
        '                queue.push(neighbor);',
        '            }',
        '        }',
        '    }',
        '}',
      ],
      lineHighlights: {
        2: '初始化访问集合',
        3: '初始化队列',
        4: '标记起始节点',
        6: '队列不为空',
        7: '出队节点',
        8: '访问节点',
        9: '遍历邻居',
        10: '未访问',
        11: '标记已访问',
        12: '邻居入队',
      },
    },
  },
  dfs: {
    python: {
      language: 'python',
      lines: [
        'def dfs(graph, start, visited=None):',
        '    if visited is None:',
        '        visited = set()',
        '    ',
        '    visited.add(start)',
        '    print(start)',
        '    ',
        '    for neighbor in graph[start]:',
        '        if neighbor not in visited:',
        '            dfs(graph, neighbor, visited)',
      ],
      lineHighlights: {
        2: '初始化访问集合',
        4: '标记已访问',
        5: '访问节点',
        7: '遍历邻居',
        8: '未访问',
        9: '递归深度优先',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function dfs(graph, start, visited = new Set()) {',
        '    visited.add(start);',
        '    console.log(start);',
        '    ',
        '    for (const neighbor of graph[start]) {',
        '        if (!visited.has(neighbor)) {',
        '            dfs(graph, neighbor, visited);',
        '        }',
        '    }',
        '}',
      ],
      lineHighlights: {
        2: '标记已访问',
        3: '访问节点',
        5: '遍历邻居',
        6: '未访问',
        7: '递归深度优先',
      },
    },
  },
  dijkstra: {
    python: {
      language: 'python',
      lines: [
        'import heapq',
        '',
        'def dijkstra(graph, start):',
        '    dist = {node: float("inf") for node in graph}',
        '    dist[start] = 0',
        '    pq = [(0, start)]',
        '    ',
        '    while pq:',
        '        d, node = heapq.heappop(pq)',
        '        if d > dist[node]:',
        '            continue',
        '        for neighbor, weight in graph[node]:',
        '            new_dist = dist[node] + weight',
        '            if new_dist < dist[neighbor]:',
        '                dist[neighbor] = new_dist',
        '                heapq.heappush(pq, (new_dist, neighbor))',
        '    return dist',
      ],
      lineHighlights: {
        4: '初始化距离',
        5: '起始距离为0',
        6: '优先级队列',
        8: '队列不为空',
        9: '取最小距离节点',
        10: '跳过已处理',
        11: '遍历邻居',
        12: '计算新距离',
        13: '更短路径',
        14: '更新距离',
        15: '加入队列',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function dijkstra(graph, start) {',
        '    const dist = {};',
        '    for (const node in graph) {',
        '        dist[node] = Infinity;',
        '    }',
        '    dist[start] = 0;',
        '    const pq = [[0, start]];',
        '    ',
        '    while (pq.length > 0) {',
        '        const [d, node] = pq.shift();',
        '        if (d > dist[node]) continue;',
        '        for (const [neighbor, weight] of graph[node]) {',
        '            const newDist = dist[node] + weight;',
        '            if (newDist < dist[neighbor]) {',
        '                dist[neighbor] = newDist;',
        '                pq.push([newDist, neighbor]);',
        '            }',
        '        }',
        '    }',
        '    return dist;',
        '}',
      ],
      lineHighlights: {
        2: '初始化距离对象',
        3: '遍历节点',
        4: '距离设为无穷大',
        5: '起始距离为0',
        6: '优先级队列',
        8: '队列不为空',
        9: '取最小距离节点',
        10: '跳过已处理',
        11: '遍历邻居',
        12: '计算新距离',
        13: '更短路径',
        14: '更新距离',
        15: '加入队列',
      },
    },
  },
  stack: {
    python: {
      language: 'python',
      lines: [
        'class Stack:',
        '    def __init__(self):',
        '        self.items = []',
        '    ',
        '    def push(self, item):',
        '        self.items.append(item)',
        '    ',
        '    def pop(self):',
        '        if not self.is_empty():',
        '            return self.items.pop()',
        '    ',
        '    def peek(self):',
        '        if not self.is_empty():',
        '            return self.items[-1]',
        '    ',
        '    def is_empty(self):',
        '        return len(self.items) == 0',
      ],
      lineHighlights: {
        1: '栈类定义',
        2: '初始化',
        4: '入栈操作',
        5: '添加到末尾',
        7: '出栈操作',
        8: '检查非空',
        9: '移除末尾元素',
        11: '查看栈顶',
        12: '检查非空',
        13: '返回末尾元素',
        15: '判空操作',
        16: '检查长度',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'class Stack {',
        '    constructor() {',
        '        this.items = [];',
        '    }',
        '    ',
        '    push(item) {',
        '        this.items.push(item);',
        '    }',
        '    ',
        '    pop() {',
        '        if (!this.isEmpty()) {',
        '            return this.items.pop();',
        '        }',
        '    }',
        '    ',
        '    peek() {',
        '        if (!this.isEmpty()) {',
        '            return this.items[this.items.length - 1];',
        '        }',
        '    }',
        '    ',
        '    isEmpty() {',
        '        return this.items.length === 0;',
        '    }',
        '}',
      ],
      lineHighlights: {
        1: '栈类定义',
        2: '初始化',
        3: '数组存储',
        5: '入栈操作',
        6: '添加到末尾',
        8: '出栈操作',
        9: '检查非空',
        10: '移除末尾元素',
        12: '查看栈顶',
        13: '检查非空',
        14: '返回末尾元素',
        16: '判空操作',
        17: '检查长度',
      },
    },
  },
  queue: {
    python: {
      language: 'python',
      lines: [
        'from collections import deque',
        '',
        'class Queue:',
        '    def __init__(self):',
        '        self.items = deque()',
        '    ',
        '    def enqueue(self, item):',
        '        self.items.append(item)',
        '    ',
        '    def dequeue(self):',
        '        if not self.is_empty():',
        '            return self.items.popleft()',
        '    ',
        '    def front(self):',
        '        if not self.is_empty():',
        '            return self.items[0]',
        '    ',
        '    def is_empty(self):',
        '        return len(self.items) == 0',
      ],
      lineHighlights: {
        4: '队列类定义',
        5: '初始化',
        6: '使用双端队列',
        8: '入队操作',
        9: '添加到末尾',
        11: '出队操作',
        12: '检查非空',
        13: '移除首部元素',
        15: '查看队首',
        16: '检查非空',
        17: '返回首部元素',
        19: '判空操作',
        20: '检查长度',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'class Queue {',
        '    constructor() {',
        '        this.items = [];',
        '    }',
        '    ',
        '    enqueue(item) {',
        '        this.items.push(item);',
        '    }',
        '    ',
        '    dequeue() {',
        '        if (!this.isEmpty()) {',
        '            return this.items.shift();',
        '        }',
        '    }',
        '    ',
        '    front() {',
        '        if (!this.isEmpty()) {',
        '            return this.items[0];',
        '        }',
        '    }',
        '    ',
        '    isEmpty() {',
        '        return this.items.length === 0;',
        '    }',
        '}',
      ],
      lineHighlights: {
        1: '队列类定义',
        2: '初始化',
        3: '数组存储',
        5: '入队操作',
        6: '添加到末尾',
        8: '出队操作',
        9: '检查非空',
        10: '移除首部元素',
        12: '查看队首',
        13: '检查非空',
        14: '返回首部元素',
        16: '判空操作',
        17: '检查长度',
      },
    },
  },
  linkedList: {
    python: {
      language: 'python',
      lines: [
        'class Node:',
        '    def __init__(self, val):',
        '        self.val = val',
        '        self.next = None',
        '',
        'class LinkedList:',
        '    def __init__(self):',
        '        self.head = None',
        '    ',
        '    def insert(self, val):',
        '        new_node = Node(val)',
        '        if not self.head:',
        '            self.head = new_node',
        '            return',
        '        curr = self.head',
        '        while curr.next:',
        '            curr = curr.next',
        '        curr.next = new_node',
        '    ',
        '    def delete(self, val):',
        '        if not self.head: return',
        '        if self.head.val == val:',
        '            self.head = self.head.next',
        '            return',
        '        curr = self.head',
        '        while curr.next:',
        '            if curr.next.val == val:',
        '                curr.next = curr.next.next',
        '                return',
        '            curr = curr.next',
        '    ',
        '    def search(self, val):',
        '        curr = self.head',
        '        while curr:',
        '            if curr.val == val:',
        '                return curr',
        '            curr = curr.next',
        '        return None',
      ],
      lineHighlights: {
        1: '节点类定义',
        2: '初始化节点',
        3: '存储值',
        4: '指向下一个节点',
        6: '链表类定义',
        7: '初始化链表',
        8: '头节点为None',
        10: '插入操作',
        11: '创建新节点',
        12: '空链表',
        13: '设为头节点',
        14: '遍历到尾节点',
        15: '移动到下一个',
        17: '删除操作',
        18: '空链表',
        19: '删除头节点',
        24: '搜索操作',
        25: '从头部开始',
        26: '遍历链表',
        27: '找到目标',
        28: '返回节点',
        30: '未找到',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'class Node {',
        '    constructor(val) {',
        '        this.val = val;',
        '        this.next = null;',
        '    }',
        '}',
        '',
        'class LinkedList {',
        '    constructor() {',
        '        this.head = null;',
        '    }',
        '    ',
        '    insert(val) {',
        '        const newNode = new Node(val);',
        '        if (!this.head) {',
        '            this.head = newNode;',
        '            return;',
        '        }',
        '        let curr = this.head;',
        '        while (curr.next) {',
        '            curr = curr.next;',
        '        }',
        '        curr.next = newNode;',
        '    }',
        '    ',
        '    delete(val) {',
        '        if (!this.head) return;',
        '        if (this.head.val === val) {',
        '            this.head = this.head.next;',
        '            return;',
        '        }',
        '        let curr = this.head;',
        '        while (curr.next) {',
        '            if (curr.next.val === val) {',
        '                curr.next = curr.next.next;',
        '                return;',
        '            }',
        '            curr = curr.next;',
        '        }',
        '    }',
        '    ',
        '    search(val) {',
        '        let curr = this.head;',
        '        while (curr) {',
        '            if (curr.val === val) {',
        '                return curr;',
        '            }',
        '            curr = curr.next;',
        '        }',
        '        return null;',
        '    }',
        '}',
      ],
      lineHighlights: {
        1: '节点类定义',
        2: '初始化节点',
        3: '存储值',
        4: '指向下一个节点',
        6: '链表类定义',
        7: '初始化链表',
        8: '头节点为null',
        10: '插入操作',
        11: '创建新节点',
        12: '空链表',
        13: '设为头节点',
        14: '遍历到尾节点',
        15: '移动到下一个',
        17: '删除操作',
        18: '空链表',
        19: '删除头节点',
        24: '搜索操作',
        25: '从头部开始',
        26: '遍历链表',
        27: '找到目标',
        28: '返回节点',
        30: '未找到',
      },
    },
  },
};
