export interface CodeSnippet {
  language: 'python' | 'javascript';
  lines: string[];
  lineHighlights: Record<number, string>;
}

export interface AlgorithmCode {
  python: CodeSnippet;
  javascript: CodeSnippet;
}

export const ALGORITHM_CODE: Record<string, AlgorithmCode> = {
  bubbleSort: {
    python: {
      language: 'python',
      lines: [
        'def bubble_sort(arr):',
        '    n = len(arr)',
        '    for i in range(n - 1):',
        '        for j in range(n - i - 1):',
        '            if arr[j] > arr[j + 1]:',
        '                arr[j], arr[j + 1] = arr[j + 1], arr[j]',
        '    return arr',
      ],
      lineHighlights: {
        2: '外层循环开始',
        3: '内层循环开始',
        4: '比较相邻元素',
        5: '如果左边大于右边',
        6: '交换元素',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function bubbleSort(arr) {',
        '    const n = arr.length;',
        '    for (let i = 0; i < n - 1; i++) {',
        '        for (let j = 0; j < n - i - 1; j++) {',
        '            if (arr[j] > arr[j + 1]) {',
        '                [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];',
        '            }',
        '        }',
        '    }',
        '    return arr;',
        '}',
      ],
      lineHighlights: {
        2: '获取数组长度',
        3: '外层循环',
        4: '内层循环',
        5: '比较相邻元素',
        6: '交换元素',
      },
    },
  },
  selectionSort: {
    python: {
      language: 'python',
      lines: [
        'def selection_sort(arr):',
        '    n = len(arr)',
        '    for i in range(n - 1):',
        '        min_idx = i',
        '        for j in range(i + 1, n):',
        '            if arr[j] < arr[min_idx]:',
        '                min_idx = j',
        '        arr[i], arr[min_idx] = arr[min_idx], arr[i]',
        '    return arr',
      ],
      lineHighlights: {
        2: '获取数组长度',
        3: '外层循环',
        4: '假设最小值索引',
        5: '内层循环查找最小值',
        6: '更新最小值索引',
        7: '交换元素到正确位置',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function selectionSort(arr) {',
        '    const n = arr.length;',
        '    for (let i = 0; i < n - 1; i++) {',
        '        let minIdx = i;',
        '        for (let j = i + 1; j < n; j++) {',
        '            if (arr[j] < arr[minIdx]) {',
        '                minIdx = j;',
        '            }',
        '        }',
        '        [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];',
        '    }',
        '    return arr;',
        '}',
      ],
      lineHighlights: {
        2: '获取数组长度',
        3: '外层循环',
        4: '假设最小值索引',
        5: '内层循环查找最小值',
        6: '更新最小值索引',
        9: '交换元素到正确位置',
      },
    },
  },
  insertionSort: {
    python: {
      language: 'python',
      lines: [
        'def insertion_sort(arr):',
        '    for i in range(1, len(arr)):',
        '        key = arr[i]',
        '        j = i - 1',
        '        while j >= 0 and arr[j] > key:',
        '            arr[j + 1] = arr[j]',
        '            j -= 1',
        '        arr[j + 1] = key',
        '    return arr',
      ],
      lineHighlights: {
        2: '从第二个元素开始',
        3: '保存当前元素',
        4: '初始化比较位置',
        5: '向前移动较大元素',
        6: '元素右移',
        7: '移动指针',
        8: '插入到正确位置',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function insertionSort(arr) {',
        '    for (let i = 1; i < arr.length; i++) {',
        '        const key = arr[i];',
        '        let j = i - 1;',
        '        while (j >= 0 && arr[j] > key) {',
        '            arr[j + 1] = arr[j];',
        '            j--;',
        '        }',
        '        arr[j + 1] = key;',
        '    }',
        '    return arr;',
        '}',
      ],
      lineHighlights: {
        2: '从第二个元素开始',
        3: '保存当前元素',
        4: '初始化比较位置',
        5: '向前移动较大元素',
        6: '元素右移',
        7: '移动指针',
        9: '插入到正确位置',
      },
    },
  },
  quickSort: {
    python: {
      language: 'python',
      lines: [
        'def quick_sort(arr, low, high):',
        '    if low < high:',
        '        pi = partition(arr, low, high)',
        '        quick_sort(arr, low, pi - 1)',
        '        quick_sort(arr, pi + 1, high)',
        '',
        'def partition(arr, low, high):',
        '    pivot = arr[high]',
        '    i = low - 1',
        '    for j in range(low, high):',
        '        if arr[j] < pivot:',
        '            i += 1',
        '            arr[i], arr[j] = arr[j], arr[i]',
        '    arr[i + 1], arr[high] = arr[high], arr[i + 1]',
        '    return i + 1',
      ],
      lineHighlights: {
        2: '基本情形',
        3: '分区操作',
        4: '递归排序左半部分',
        5: '递归排序右半部分',
        9: '选择枢轴元素',
        10: '初始化指针',
        11: '遍历数组',
        12: '小于枢轴',
        13: '交换小于枢轴的元素',
        15: '将枢轴放到正确位置',
        16: '返回枢轴索引',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function quickSort(arr, low, high) {',
        '    if (low < high) {',
        '        const pi = partition(arr, low, high);',
        '        quickSort(arr, low, pi - 1);',
        '        quickSort(arr, pi + 1, high);',
        '    }',
        '}',
        '',
        'function partition(arr, low, high) {',
        '    const pivot = arr[high];',
        '    let i = low - 1;',
        '    for (let j = low; j < high; j++) {',
        '        if (arr[j] < pivot) {',
        '            i++;',
        '            [arr[i], arr[j]] = [arr[j], arr[i]];',
        '        }',
        '    }',
        '    [arr[i + 1], arr[high]] = [arr[high], arr[i + 1]];',
        '    return i + 1;',
        '}',
      ],
      lineHighlights: {
        2: '基本情形',
        3: '分区操作',
        4: '递归排序左半部分',
        5: '递归排序右半部分',
        9: '选择枢轴元素',
        10: '初始化指针',
        11: '遍历数组',
        12: '小于枢轴',
        13: '指针右移',
        14: '交换元素',
        17: '将枢轴放到正确位置',
        18: '返回枢轴索引',
      },
    },
  },
  mergeSort: {
    python: {
      language: 'python',
      lines: [
        'def merge_sort(arr):',
        '    if len(arr) > 1:',
        '        mid = len(arr) // 2',
        '        L = arr[:mid]',
        '        R = arr[mid:]',
        '        merge_sort(L)',
        '        merge_sort(R)',
        '        merge(arr, L, R)',
        '',
        'def merge(arr, L, R):',
        '    i = j = k = 0',
        '    while i < len(L) and j < len(R):',
        '        if L[i] <= R[j]:',
        '            arr[k] = L[i]',
        '            i += 1',
        '        else:',
        '            arr[k] = R[j]',
        '            j += 1',
        '        k += 1',
      ],
      lineHighlights: {
        2: '基本情形',
        3: '找中点',
        4: '左半部分',
        5: '右半部分',
        6: '递归排序左半部分',
        7: '递归排序右半部分',
        8: '合并两半部分',
        12: '初始化指针',
        13: '比较并合并',
        14: '左边元素较小',
        15: '复制左边元素',
        17: '右边元素较小',
        18: '复制右边元素',
        20: '移动指针',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function mergeSort(arr) {',
        '    if (arr.length > 1) {',
        '        const mid = Math.floor(arr.length / 2);',
        '        const L = arr.slice(0, mid);',
        '        const R = arr.slice(mid);',
        '        mergeSort(L);',
        '        mergeSort(R);',
        '        merge(arr, L, R);',
        '    }',
        '}',
        '',
        'function merge(arr, L, R) {',
        '    let i = j = k = 0;',
        '    while (i < L.length && j < R.length) {',
        '        if (L[i] <= R[j]) {',
        '            arr[k] = L[i];',
        '            i++;',
        '        } else {',
        '            arr[k] = R[j];',
        '            j++;',
        '        }',
        '        k++;',
        '    }',
        '}',
      ],
      lineHighlights: {
        2: '基本情形',
        3: '找中点',
        4: '左半部分',
        5: '右半部分',
        6: '递归排序左半部分',
        7: '递归排序右半部分',
        8: '合并两半部分',
        12: '初始化指针',
        13: '比较并合并',
        14: '左边元素较小',
        15: '复制左边元素',
        17: '右边元素较小',
        18: '复制右边元素',
        20: '移动指针',
      },
    },
  },
  heapSort: {
    python: {
      language: 'python',
      lines: [
        'def heap_sort(arr):',
        '    n = len(arr)',
        '    for i in range(n // 2 - 1, -1, -1):',
        '        heapify(arr, n, i)',
        '    for i in range(n - 1, 0, -1):',
        '        arr[0], arr[i] = arr[i], arr[0]',
        '        heapify(arr, i, 0)',
        '',
        'def heapify(arr, n, i):',
        '    largest = i',
        '    left = 2 * i + 1',
        '    right = 2 * i + 2',
        '    if left < n and arr[left] > arr[largest]:',
        '        largest = left',
        '    if right < n and arr[right] > arr[largest]:',
        '        largest = right',
        '    if largest != i:',
        '        arr[i], arr[largest] = arr[largest], arr[i]',
        '        heapify(arr, n, largest)',
      ],
      lineHighlights: {
        2: '获取数组长度',
        3: '构建最大堆',
        4: '堆化操作',
        6: '逐个提取元素',
        7: '交换堆顶和末尾',
        8: '堆化根节点',
        12: '堆化函数',
        13: '初始化为根节点',
        14: '左子节点',
        15: '右子节点',
        16: '左子节点更大',
        18: '右子节点更大',
        20: '需要交换',
        21: '交换元素',
        22: '递归堆化',
      },
    },
    javascript: {
      language: 'javascript',
      lines: [
        'function heapSort(arr) {',
        '    const n = arr.length;',
        '    for (let i = Math.floor(n / 2) - 1; i >= 0; i--) {',
        '        heapify(arr, n, i);',
        '    }',
        '    for (let i = n - 1; i > 0; i--) {',
        '        [arr[0], arr[i]] = [arr[i], arr[0]];',
        '        heapify(arr, i, 0);',
        '    }',
        '}',
        '',
        'function heapify(arr, n, i) {',
        '    let largest = i;',
        '    const left = 2 * i + 1;',
        '    const right = 2 * i + 2;',
        '    if (left < n && arr[left] > arr[largest]) {',
        '        largest = left;',
        '    }',
        '    if (right < n && arr[right] > arr[largest]) {',
        '        largest = right;',
        '    }',
        '    if (largest !== i) {',
        '        [arr[i], arr[largest]] = [arr[largest], arr[i]];',
        '        heapify(arr, n, largest);',
        '    }',
        '}',
      ],
      lineHighlights: {
        2: '获取数组长度',
        3: '构建最大堆',
        4: '堆化操作',
        6: '逐个提取元素',
        7: '交换堆顶和末尾',
        8: '堆化根节点',
        12: '堆化函数',
        13: '初始化为根节点',
        14: '左子节点',
        15: '右子节点',
        16: '左子节点更大',
        18: '右子节点更大',
        20: '需要交换',
        21: '交换元素',
        22: '递归堆化',
      },
    },
  },
};
