class AppConstants {
  static const String appName = 'CodeVault';
  static const String appVersion = '1.0.0';

  static const List<String> defaultCodeExtensions = [
    '.dart',
    '.js',
    '.ts',
    '.jsx',
    '.tsx',
    '.py',
    '.java',
    '.c',
    '.cpp',
    '.h',
    '.hpp',
    '.cs',
    '.go',
    '.rs',
    '.rb',
    '.php',
    '.swift',
    '.kt',
    '.scala',
    '.html',
    '.css',
    '.scss',
    '.sass',
    '.less',
    '.json',
    '.xml',
    '.yaml',
    '.yml',
    '.md',
    '.sql',
    '.sh',
    '.bash',
    '.zsh',
    '.ps1',
    '.bat',
    '.cmd',
    '.dockerfile',
    '.gitignore',
    '.env',
    '.properties',
    '.toml',
    '.ini',
    '.cfg',
    '.conf',
  ];

  static const Map<String, String> languageMap = {
    'dart': 'Dart',
    'js': 'JavaScript',
    'ts': 'TypeScript',
    'jsx': 'JavaScript React',
    'tsx': 'TypeScript React',
    'py': 'Python',
    'java': 'Java',
    'c': 'C',
    'cpp': 'C++',
    'h': 'C Header',
    'hpp': 'C++ Header',
    'cs': 'C#',
    'go': 'Go',
    'rs': 'Rust',
    'rb': 'Ruby',
    'php': 'PHP',
    'swift': 'Swift',
    'kt': 'Kotlin',
    'scala': 'Scala',
    'html': 'HTML',
    'css': 'CSS',
    'scss': 'SCSS',
    'sass': 'Sass',
    'less': 'Less',
    'json': 'JSON',
    'xml': 'XML',
    'yaml': 'YAML',
    'yml': 'YAML',
    'md': 'Markdown',
    'sql': 'SQL',
    'sh': 'Shell',
    'bash': 'Bash',
    'zsh': 'Zsh',
    'ps1': 'PowerShell',
    'bat': 'Batch',
    'cmd': 'Batch',
    'dockerfile': 'Dockerfile',
    'gitignore': 'Git Ignore',
    'env': 'Environment',
    'properties': 'Properties',
    'toml': 'TOML',
    'ini': 'INI',
    'cfg': 'Configuration',
    'conf': 'Configuration',
    'txt': 'Plain Text',
    'log': 'Log',
    'csv': 'CSV',
  };

  static const double minFontSize = 10.0;
  static const double maxFontSize = 24.0;
  static const double defaultFontSize = 14.0;

  static const int defaultTabWidth = 2;
  static const List<int> tabWidthOptions = [2, 4, 8];
}
